# Generated by Django 5.1.1 on 2024-10-16 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('control_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(choices=[('B_NEW', 'Brand New'), ('NEW_SD', 'New Scratch&Dent'), ('USED', 'Used'), ('REFURB', 'Refurbished')], max_length=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_type', models.CharField(choices=[('STORE_1', 'Store One Year'), ('STORE_90', 'Store 90 Days'), ('STORE_30', 'Store 30 Days'), ('STORE_2', 'Store Two Years'), ('STORE_3', 'Store Three Years'), ('STORE_4', 'Store Four Years'), ('STORE_5', 'Store Five Years'), ('MANUF_1', 'Manufacturer One Year'), ('CPS_1', 'CPS One Year'), ('CPS_2', 'CPS Two Years'), ('CPS_3', 'CPS Three Years'), ('CPS_4', 'CPS Four Years'), ('NONE', 'None')], max_length=10)),
                ('current_state', models.CharField(choices=[('RECEIV', 'Receiving'), ('TEST', 'Testing'), ('SCRAP', 'Scrap'), ('IN_STOCK', 'In Stock'), ('SOLD', 'Sold'), ('RETURNED', 'Returned')], max_length=10)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posdash.vendor')),
            ],
        ),
    ]
