# Generated by Django 5.1.1 on 2024-10-16 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_model_images/')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('product_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feature')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
    ]
