# Generated by Django 5.1.1 on 2024-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
