# Generated by Django 5.1.1 on 2024-10-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='product_model',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
    ]
