# Generated by Django 5.1.1 on 2024-10-22 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productfeature_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('product_spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.spec')),
            ],
        ),
    ]
