# Generated by Django 5.1.1 on 2024-10-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimage_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
